#!/bin/bash

http https://www.facebook.com
http https://www.twitter.com
http https://www.google.com
http https://www.youtube.com
http https://www.instagram.com
http https://www.linkedin.com
http https://www.wordpress.org
http https://www.pinterest.com
http https://www.wikipedia.org
http https://www.wordpress.com
http https://www.blogspot.com
http https://www.apple.com
http https://www.adobe.com
http https://www.tumblr.com
http https://www.youtu.be
http https://www.amazon.com
http https://www.goo.gl
http https://www.vimeo.com
http https://www.flickr.com
http https://www.microsoft.com
http https://www.yahoo.com
http https://www.godaddy.com
http https://www.qq.com
http https://www.bit.ly
http https://www.vk.com
http https://www.reddit.com
http https://www.w3.org
http https://www.baidu.com
http https://www.nytimes.com
http https://www.t.co
http https://www.europa.eu
http https://www.buydomains.com
http https://www.wp.com
http https://www.statcounter.com
http https://www.miitbeian.gov.cn
http https://www.jimdo.com
http https://www.blogger.com
http https://www.github.com
http https://www.weebly.com
http https://www.soundcloud.com
http https://www.mozilla.org
http https://www.bbc.co.uk
http https://www.yandex.ru
http https://www.myspace.com
http https://www.google.de
http https://www.addthis.com
http https://www.nih.gov
http https://www.theguardian.com
http https://www.google.co.jp
http https://www.cnn.com
http https://www.stumbleupon.com
http https://www.gravatar.com
http https://www.digg.com
http https://www.addtoany.com
http https://www.creativecommons.org
http https://www.paypal.com
http https://www.yelp.com
http https://www.imdb.com
http https://www.huffingtonpost.com
http https://www.feedburner.com
http https://www.issuu.com
http https://www.wixsite.com
http https://www.wix.com
http https://www.dropbox.com
http https://www.forbes.com
http https://www.miibeian.gov.cn
http https://www.amazonaws.com
http https://www.google.co.uk
http https://www.washingtonpost.com
http https://www.bluehost.com
http https://www.etsy.com
http https://www.go.com
http https://www.msn.com
http https://www.wsj.com
http https://www.ameblo.jp
http https://www.archive.org
http https://www.slideshare.net
http https://www.e-recht24.de
http https://www.weibo.com
http https://www.fc2.com
http https://www.eventbrite.com
http https://www.parallels.com
http https://www.doubleclick.net
http https://www.mail.ru
http https://www.sourceforge.net
http https://www.amazon.co.uk
http https://www.telegraph.co.uk
http https://www.ebay.com
http https://www.amzn.to
http https://www.livejournal.com
http https://www.51.la
http https://www.free.fr
http https://www.yahoo.co.jp
http https://www.dailymail.co.uk
http https://www.reuters.com
http https://www.taobao.com
http https://www.wikimedia.org
http https://www.amazon.de
http https://www.typepad.com
http https://www.hatena.ne.jp
http https://www.bloomberg.com
http https://www.elegantthemes.com
http https://www.eepurl.com
http https://www.usatoday.com
http https://www.about.com
http https://www.medium.com
http https://www.macromedia.com
http https://www.xing.com
http https://www.bing.com
http https://www.time.com
http https://www.www.gov.uk
http https://www.google.it
http https://www.cdc.gov
http https://www.tripadvisor.com
http https://www.cpanel.net
http https://www.amazon.co.jp
http https://www.npr.org
http https://www.harvard.edu
http https://www.bbb.org
http https://www.aol.com
http https://www.constantcontact.com
http https://www.latimes.com
http https://www.icio.us
http https://www.list-manage.com
http https://www.webs.com
http https://www.opera.com
http https://www.beian.gov.cn
http https://www.vkontakte.ru
http https://www.blogspot.co.uk
http https://www.live.com
http https://www.bandcamp.com
http https://www.apache.org
http https://www.bbc.com
http https://www.businessinsider.com
http https://www.dailymotion.com
http https://www.cpanel.com
http https://www.disqus.com
http https://www.behance.net
http https://www.mit.edu
http https://www.rambler.ru
http https://www.gnu.org
http https://www.sina.com.cn
http https://www.spotify.com
http https://www.joomla.org
http https://www.google.es
http https://www.line.me
http https://www.wired.com
http https://www.github.io
http https://www.stanford.edu
http https://www.googleusercontent.com
http https://www.kickstarter.com
http https://www.guardian.co.uk
http https://www.imgur.com
http https://www.google.fr
http https://www.goodreads.com
http https://www.nasa.gov
http https://www.rakuten.co.jp
http https://www.surveymonkey.com
http https://www.delicious.com
http https://www.independent.co.uk
http https://www.whatsapp.com
http https://www.one.com
http https://www.photobucket.com
http https://www.ted.com
http https://www.themeforest.net
http https://www.homestead.com
http https://www.google.ca
http https://www.cnet.com
http https://www.1und1.de
http https://www.deviantart.com
http https://www.scribd.com
http https://www.jiathis.com
http https://www.domainname.de
http https://www.ca.gov
http https://www.shopify.com
http https://www.plesk.com
http https://www.wiley.com
http https://www.who.int
http https://www.un.org
http https://www.buzzfeed.com
http https://www.theatlantic.com
http https://www.barnesandnoble.com
http https://www.sakura.ne.jp
http https://www.pbs.org
http https://www.nationalgeographic.com
http https://www.getpocket.com
http https://www.blogspot.com.es
http https://www.nature.com
http https://www.networksolutions.com
http https://www.webmd.com
http https://www.foxnews.com
http https://www.cbsnews.com
http https://www.techcrunch.com
http https://www.booking.com
http https://www.php.net
http https://www.berkeley.edu
http https://www.cloudfront.net
http https://www.sciencedirect.com
http https://www.ibm.com
http https://www.a8.net
http https://www.163.com
http https://www.nbcnews.com
http https://www.skype.com
http https://www.mashable.com
http https://www.cornell.edu
http https://www.naver.com
http https://www.domainretailing.com
http https://www.usda.gov
http https://www.wp.me
http https://www.4.cn
http https://www.springer.com
http https://www.whitehouse.gov
http https://www.squarespace.com
http https://www.phoca.cz
http https://www.change.org
http https://www.cbc.ca
http https://www.ft.com
http https://www.epa.gov
http https://www.secureserver.net
http https://www.enable-javascript.com
http https://www.meetup.com
http https://www.noaa.gov
http https://www.cnbc.com
http https://www.nps.gov
http https://www.phpbb.com
http https://www.wikia.com
http https://www.usnews.com
http https://www.google.nl
http https://www.myshopify.com
http https://www.mapquest.com
http https://www.trustpilot.com
http https://www.domainactive.co
http https://www.uol.com.br
http https://www.foursquare.com
http https://www.ow.ly
http https://www.google.com.br
http https://www.telegram.me
http https://www.sohu.com
http https://www.loc.gov
http https://www.economist.com
http https://www.fda.gov
http https://www.irs.gov
http https://www.themegrill.com
http https://www.wufoo.com
http https://www.geocities.jp
http https://www.bigcartel.com
http https://www.livedoor.jp
http https://www.chicagotribune.com
http https://www.dribbble.com
http https://www.hp.com
http https://www.doi.org
http https://www.prnewswire.com
http https://www.ed.gov
http https://www.ok.ru
http https://www.newyorker.com
http https://www.abc.net.au
http https://www.bizjournals.com
http https://www.slate.com
http https://www.houzz.com
http https://www.umblr.com
http https://www.fb.com
http https://www.vice.com
http https://www.xinhuanet.com
http https://www.engadget.com
http https://www.nifty.com
http https://www.t.me
http https://www.marriott.com
http https://www.clickbank.net
http https://www.globo.com
http https://www.list-manage1.com
http https://www.histats.com
http https://www.state.gov
http https://www.cbslocal.com
http https://www.unesco.org
http https://www.google.com.au
http https://www.umich.edu
http https://www.hostnet.nl
http https://www.google.pl
http https://www.house.gov
http https://www.youku.com
http https://www.theverge.com
http https://www.ocn.ne.jp
http https://www.storify.com
http https://www.sogou.com
http https://www.goo.ne.jp
http https://www.fortune.com
http https://www.wunderground.com
http https://www.aboutcookies.org
http https://www.rs6.net
http https://www.columbia.edu
http https://www.namejet.com
http https://www.gofundme.com
http https://www.oracle.com
http https://www.yale.edu
http https://www.psychologytoday.com
http https://www.ifeng.com
http https://www.washington.edu
http https://www.indiatimes.com
http https://www.samsung.com
http https://www.upenn.edu
http https://www.athemes.com
http https://www.1and1.com
http https://www.studiopress.com
http https://www.hilton.com
http https://www.debian.org
http https://www.wikihow.com
http https://www.fbcdn.net
http https://www.fb.me
http https://www.senate.gov
http https://www.fastcompany.com
http https://www.mailchimp.com
http https://www.alibaba.com
http https://www.youronlinechoices.com
http https://www.android.com
http https://www.researchgate.net
http https://www.ustream.tv
http https://www.dedecms.com
http https://www.zdnet.com
http https://www.home.pl
http https://www.exblog.jp
http https://www.cryoutcreations.eu
http https://www.entrepreneur.com
http https://www.drupal.org
http https://www.sagepub.com
http https://www.tripadvisor.co.uk
http https://www.businesswire.com
http https://www.shinystat.com
http https://www.umn.edu
http https://www.jugem.jp
http https://www.hbr.org
http https://www.sciencemag.org
http https://www.ftc.gov
http https://www.1688.com
http https://www.google.co.in
http https://www.wisc.edu
http https://www.ucla.edu
http https://www.inc.com
http https://www.psu.edu
http https://www.loopia.se
http https://www.visma.com
http https://www.dreamhost.com
http https://www.mijndomein.nl
http https://www.loopia.com
http https://www.ox.ac.uk
http https://www.scientificamerican.com
http https://www.utexas.edu
http https://www.stackoverflow.com
http https://www.1and1.fr
http https://www.sedo.com
http https://www.mozilla.com
http https://www.worldbank.org
http https://www.hubspot.com
http https://www.census.gov
http https://www.arstechnica.com
http https://www.mysql.com
http https://www.si.edu
http https://www.allaboutcookies.org
http https://www.usgs.gov
http https://www.intel.com
http https://www.amazon.fr
http https://www.shop-pro.jp
http https://www.tandfonline.com
http https://www.aliyun.com
http https://www.office.com
http https://www.alexa.com
http https://www.zendesk.com
http https://www.nhk.or.jp
http https://www.colorlib.com
http https://www.accuweather.com
http https://www.cisco.com
http https://www.google.ru
http https://www.cam.ac.uk
http https://www.hibu.com
http https://www.hollywoodreporter.com
http https://www.admin.ch
http https://www.example.com
http https://www.hhs.gov
http https://www.twitch.tv
http https://www.networkadvertising.org
http https://www.nyu.edu
http https://www.teamviewer.com
http https://www.nazwa.pl
http https://www.variety.com
http https://www.netflix.com
http https://www.box.com
http https://www.prestashop.com
http https://www.bls.gov
http https://www.bmj.com
http https://www.uchicago.edu
http https://www.wsimg.com
http https://www.www.nhs.uk
http https://www.eventbrite.co.uk
http https://www.opensource.org
http https://www.zenfolio.com
http https://www.blogspot.jp
http https://www.usc.edu
http https://www.va.gov
http https://www.cmu.edu
http https://www.oecd.org
http https://www.ieee.org
http https://www.mlb.com
http https://www.ename.com.cn
http https://www.usa.gov
http https://www.steampowered.com
http https://www.google.ch
http https://www.redcross.org
http https://www.bund.de
http https://www.thehill.com
http https://www.dictionary.com
http https://www.360.cn
http https://www.hostgator.com
http https://www.icann.org
http https://www.dot.gov
http https://www.adweek.com
http https://www.fao.org
http https://www.sun.com
http https://www.iubenda.com
http https://www.gesetze-im-internet.de
http https://www.tmall.com
http https://www.today.com
http https://www.nginx.org
http https://www.xiti.com
http https://www.venturebeat.com
http https://www.snapchat.com
http https://www.ietf.org
http https://www.symantec.com
http https://www.mhlw.go.jp
http https://www.duke.edu
http https://www.japanpost.jp
http https://www.giphy.com
http https://www.netscape.com
http https://www.justgiving.com
http https://www.sec.gov
http https://www.illinois.edu
http https://www.att.com
http https://www.squareup.com
http https://www.aboutads.info
http https://www.gpo.gov
http https://www.tucowsdomains.com
http https://www.domainnameshop.com
http https://www.plos.org
http https://www.elsevier.com
http https://www.biomedcentral.com
http https://www.reference.com
http https://www.oup.com
http https://www.ssa.gov
http https://www.libsyn.com
http https://www.windowsphone.com
http https://www.ny.gov
http https://www.bigcommerce.com
http https://www.oreilly.com
http https://www.domeneshop.no
http https://www.googleapis.com
http https://www.artisteer.com
http https://www.arxiv.org
http https://www.thenextweb.com
http https://www.google.be
http https://www.gotowebinar.com
http https://www.deloitte.com
http https://www.blackberry.com
http https://www.w3schools.com
http https://www.dol.gov
http https://www.python.org
http https://www.siteorigin.com
http https://www.ewebdevelopment.com
http https://www.moz.com
http https://www.warnerbros.com
http https://www.justice.gov
http https://www.quantcast.com
http https://www.dhs.gov
http https://www.java.com
http https://www.fcc.gov
http https://www.congress.gov
http https://www.g.co
http https://www.playstation.com
http https://www.iso.org
http https://www.opencart.com
http https://www.eff.org
http https://www.ucl.ac.uk
http https://www.moodle.org
http https://www.web.de
http https://www.unsplash.com
http https://www.msdn.com
http https://www.nist.gov
http https://www.unicef.org
http https://www.mlit.go.jp
http https://www.canada.ca
http https://www.bitbucket.org
http https://www.azurewebsites.net
http https://www.nginx.com
http https://www.dmca.com
http https://www.etracker.de
http https://www.mynavi.jp
http https://www.aarp.org
http https://www.gartner.com
http https://www.starwoodhotels.com
http https://www.typeform.com
http https://www.acm.org
http https://www.sedoparking.com
http https://www.ticketmaster.com